### ISSUE TITLE
Get-EXOMailboxPermission : An error occurred while processing this request

### ISSUE THREAD

**Issue by DavisHenckel** [MicrosoftDocs/office-docs-powershell#10142]
Hello, I'm not sure if this is the correct place to leave this issue, but I was not able to find an alternate place. I'm running to an issue on a Windows Server 2016, build 1607 with the `Get-EXOMailboxPermission` command. I'm trying to migrate my AD scripts from the older cmdlets found here: https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2.

I can run the command fine on my Windows 10 development workstation, but on the server I get a vague error. I added the `-Verbose` parameter but unfortunately it also isn't super helpful to me. I also discovered there is a typo in the error message *"An server side error occurred."* should be *"A server side error occurred"*

Here are the full details of my error message along with my PSVersionTable
```pwsh

Name                           Value
----                           -----
PSVersion                      5.1.14393.5127
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5127
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

VERBOSE: Running Get-ExoMailboxPermission
VERBOSE: [ThreadID: #] Using AuthStrategy : Default
VERBOSE: [ThreadID: #] Updating User Info based on token
VERBOSE: [ThreadID: #] Valid token is found in the cache.
Get-EXOMailboxPermission : An error occurred while processing this request..
At line:1 char:39
+ ... MailboxName" | Get-EXOMailboxPermission -User "mycompanyemail@***.com" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ProtocolError: (:) [Get-EXOMailboxPermission], Exception
    + FullyQualifiedErrorId : One or more errors occurred.,Microsoft.Exchange.Management.RestApiClient.GetExoMailboxPermission

VERBOSE: Total number of objects returned: 0
VERBOSE: [ThreadID: #13570] Using AuthStrategy : Default
VERBOSE: [ThreadID: #13570] Got valid token from cache
VERBOSE: [ThreadID: #13570] Updating User Info based on token
VERBOSE: [ThreadID: #13570] Valid token is found in the cache.
VERBOSE: [ThreadID: #13570] Service warnings are disabled. Not printing them.
VERBOSE: [ThreadID: #13570] Error fetching results: Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request. ---> Microsoft.OData.Client.DataServiceClientException:
{"error":{"code":"NotFound","message":"An server side error occured.","innererror":{"message":"An server side error occured.","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException","stacktrace":"   at
Microsoft.Exchange.Admin.OData.Core.Handlers.QueryHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage responseMessage)\r\n   at
Microsoft.Exchange.Admin.OData.Core.Handlers.RequestHandler.Process(Stream requestStream)"}}}
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at Microsoft.Exchange.Management.AdminApiProvider.ApiProvider`1.<>c__DisplayClass38_0.<InvokeRestApiWithRetry>b__1()
   at Microsoft.Exchange.Management.AdminApiProvider.ApiProvider`1.ProcessWithRetry[TRetType](Func`1 queryExecutor, Container context, String requestURL, DataServiceContext dataServiceContext)
VERBOSE: [ThreadID: #13570] HTTP Status Code: 404
VERBOSE: [ThreadID: #13570] Non-Retry-able error encountered : Microsoft.OData.Client.DataServiceQueryException: An error occurred while processing this request. ---> Microsoft.OData.Client.DataServiceClientException:
{"error":{"code":"NotFound","message":"An server side error occured.","innererror":{"message":"An server side error occured.","type":"Microsoft.Exchange.Admin.OData.Core.ODataServiceException","stacktrace":"   at
Microsoft.Exchange.Admin.OData.Core.Handlers.QueryHandler.Process(IODataRequestMessage requestMessage, IODataResponseMessage responseMessage)\r\n   at
Microsoft.Exchange.Admin.OData.Core.Handlers.RequestHandler.Process(Stream requestStream)"}}}
   at Microsoft.OData.Client.QueryResult.ExecuteQuery()
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at Microsoft.Exchange.Management.AdminApiProvider.ApiProvider`1.<>c__DisplayClass38_0.<InvokeRestApiWithRetry>b__1()
   at Microsoft.Exchange.Management.AdminApiProvider.ApiProvider`1.ProcessWithRetry[TRetType](Func`1 queryExecutor, Container context, String requestURL, DataServiceContext dataServiceContext)
PS C:\Windows\system32>
```

It's worth noting that the alternate command `Get-MailboxPermission` works as expected and returns no error, even when using the `Get-EXOMailbox` command. 

If there is a different place to submit this issue, please let me know and I will post it there.

Thank you!

**Comment by chrisda** [comment]
@DavisHenckel, a few questions:

- Which version of the ExchangeOnlineManagement module are you using? v3.0.0 is current.
- If you're using v3.0.0, are you connecting with or without the _UseRPSSession_ switch as explained [here](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#updates-for-version-300-the-exo-v3-module)? Whatever way you're currently using, try the other way to see if that makes a difference.
- I presume you're not connecting using [certificate-based authentication (CBA)](https://learn.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2)? In the off chance that you are, try connecting using the regular method.

v3.0.0 is the official release, so you can open a support ticket if you're having problems.

**Comment by DavisHenckel** [comment]
Hi @chrisda,

Thanks for the quick response.
- I am using v3.0.0 
```pwsh
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.0      ExchangeOnlineManagement            {Get-ConnectionInformation, Get-EXOCasMailbox, Get-EXOMailbox, Get-EXOMailboxFolderPermission...}
```
- I was connecting without `-UseRPSSession` so I tried switching to include the -UseRPSSession but encountered the same result. 
- No, I am not using CBA.

Thank you for that info. I have collected the errors as described in the document you linked and will send them to exocmdletpreview@service.microsoft.com

**Comment by chrisda** [comment]
Actually, don't send it to them; that alias is for feature requests and support for Preview versions of the module. A support ticket is your best way forward.

**Comment by DavisHenckel** [comment]
Just meaning a generic support ticket to Microsoft? I think my company uses a vendor as the primary before it reaches Microsoft.

**Comment by chrisda** [comment]
Use whatever method that you're comfortable with.
