### ISSUE TITLE
M$ shame #16182: M$ `Connect-IPPSSession` ignores the PowerShell most basic best practices

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/office-docs-powershell#10728]
Hello

It is extremely frightening that because of the apparently complete lack of M$ quality assurance, hardly a day goes by when we stumble across a new M$ disgrace.

Tody, we had to see that M$ PowerShell Modules ignores PowerShell most basic best practices.
For example, if you:

1. Open PowerShell **not** elevated
2. Start `Connect-IPPSSession` and use a Certificate Thumbprint
3. Then you get:
```
Error Acquiring Token:
System.Security.Cryptography.CryptographicException: Keyset does not exist
   at System.Security.Cryptography.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.CertificatePal.<>c.<GetRSAPrivateKey>b__66_0(CspParameters csp)
   at System.Security.Cryptography.X509Certificates.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at System.Security.Cryptography.X509Certificates.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.Identity.Client.PlatformsCommon.Shared.CommonCryptographyManager.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(X509Certificate2 certificate, String base64EncodedThumbprint, Boolean sendX5C)
   at Microsoft.Identity.Client.Internal.ClientCredential.CertificateAndClaimsClientCredential.AddConfidentialClientParametersAsync(OAuth2Client oAuth2Client, ILoggerAdapter logger, ICryptographyManager cryptographyManager, String clientId, String tokenEndpoint, Boolean sendX5C, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.OAuth2.TokenClient.AddBodyParamsAndHeadersAsync(IDictionary`2 additionalBodyParameters, String scopes, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.MSALTokenProvider.GetAccessTokenAsync(String claims, String cmdletId)
```

Now, try to get rid of this Error. The Microsoft Developer had no idea how to handle it.

Wouldn't minimal decency demand that M$ hire professional engineers, at least for critical software, who have a little more than a few weeks of software engineering and basic ChatGPT knowhow and have mastered the advanced software engineering.

Thanks a lot, kind regards,
Thomas

**Comment by chrisda** [comment]
@schittli, are you using the current version of the module (v3.1.0)? If so, try using the latest Preview version of the module (v3.2.0-Preview2) to see if that helps.

Connect-IPPSSession isn't as far along/mature as Connect-ExchangeOnline regarding CBA or the eventual support for REST-based connections.

And, we fix documentation here. I don't see anything documentation-related in your opening statement.

**Comment by yogkumgit** [comment]
@schittli Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
