### ISSUE TITLE
Sync-CsOnlineApplicationInstance fails with parse error: ParserException/Expected '{' or '['. Was String:

### ISSUE THREAD

**Issue by ErwinWiegman** [MicrosoftDocs/office-docs-powershell#11175]
This is tested with teams PowerShell 5.2.0 and 5.5.0. When doing a Sync-CsOnlineApplicationInstance to sync up a teams resource account, this errors out with the errorcode below. Looks like a bug at the backend of teams somewhere

PS C:\Users\> Sync-CsOnlineApplicationInstance -ObjectID $Instance.ObjectID

Correlation id for this request : b66eeef0-0b40-471d-92a3-717313ee5f30
ParserException/Expected '{' or '['. Was String: Microsoft.Ic3.TenantAdminApi.Exceptions.RestApiException: Failed to update application instance in APS.
   at Microsoft.Ic3.AdminConfig.RP.PlatformService.Controllers.ApplicationInstanceV2Controller.<SyncApsAppEndpoint>d__36.MoveNext() in /_/PlatformService/Controller/v2/Controllers/ApplicationInstanceV2Controller.cs:line 959
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Ic3.AdminConfig.RP.PlatformService.Controllers.ApplicationInstanceV2Controller.<SyncApplicationInstanceAsync>d__24.MoveNext() in /_/PlatformService/Controller/v2/Controllers/ApplicationInstanceV2Controller.cs:line 597./   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonParser.ReadNode()
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(String text)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.RestException..ctor(HttpResponseMessage response)
Sync-CsOnlineApplicationInstance: The server responded with a Server Error, Status: InternalServerError

With the debug switch get this information: 

PS C:\Users\>Sync-CsOnlineApplicationInstance -ObjectID $Instance.ObjectID -debug
VERBOSE: EnabledForFlight: True, AutoRestCommandInfo: True

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:

Confirm
Are you sure you want to perform this action?
Performing the operation "Sync-CsOnlineApplicationInstanceV2_Sync" on target "Call remote 'OnlineApplicationInstanceV2Sync' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: CmdletProcessRecordAsyncStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /Teams.PlatformService/v2/ApplicationInstances/c3fa22f1-89f5-4ee9-bc37-041242368e7c/sync
DEBUG: RequestCreated: /Teams.PlatformService/v2/ApplicationInstances/c3fa22f1-89f5-4ee9-bc37-041242368e7c/sync
DEBUG: HeaderParametersAdded:
DEBUG: SetExecutionId: 34931bf5-3fda-4641-9043-a28ae1077ec1
DEBUG: BeforeCall:
Correlation id for this request : bcb19f78-cc58-454b-9a4f-e31c46587da7
DEBUG: ResponseCreated:
ParserException/Expected '{' or '['. Was String: Microsoft.Ic3.TenantAdminApi.Exceptions.RestApiException: Failed to update application instance in APS.
   at Microsoft.Ic3.AdminConfig.RP.PlatformService.Controllers.ApplicationInstanceV2Controller.<SyncApsAppEndpoint>d__36.MoveNext() in /_/PlatformService/Controller/v2/Controllers/ApplicationInstanceV2Controller.cs:line 959
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Ic3.AdminConfig.RP.PlatformService.Controllers.ApplicationInstanceV2Controller.<SyncApplicationInstanceAsync>d__24.MoveNext() in /_/PlatformService/Controller/v2/Controllers/ApplicationInstanceV2Controller.cs:line 597./   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonParser.ReadNode()
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(String text)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.RestException..ctor(HttpResponseMessage response)
DEBUG: Finally:
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: CmdletEndProcessing:
Sync-CsOnlineApplicationInstance: The server responded with a Server Error, Status: InternalServerError

**Comment by Hank-TNguyen** [comment]
Sync-CsOnlineApplicationInstance -ObjectID <guid> -ApplicationId <guid> 
@yogkumgit can you try with the syntax above?

**Comment by ErwinWiegman** [comment]
Hi Hank, this does not make a difference, same issue

Sync-CsOnlineApplicationInstance -ObjectId c3fa22f1-89f5-4ee9-bc37-041242368e7c

Correlation id for this request : 88ed1f66-ad7a-4786-bf33-3de834ad9d08
ParserException/Expected '{' or '['. Was String: Microsoft.Ic3.TenantAdminApi.Exceptions.RestApiException: Failed to update application instance in APS.
   at Microsoft.Ic3.AdminConfig.RP.PlatformService.Controllers.ApplicationInstanceV2Controller.<SyncApsAppEndpoint>d__36.MoveNext() in /_/PlatformService/Controller/v2/Controllers/ApplicationInstanceV2Controller.cs:line 959
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Ic3.AdminConfig.RP.PlatformService.Controllers.ApplicationInstanceV2Controller.<SyncApplicationInstanceAsync>d__24.MoveNext() in /_/PlatformService/Controller/v2/Controllers/ApplicationInstanceV2Controller.cs:line 597./   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonParser.ReadNode()
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(String text)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.RestException..ctor(HttpResponseMessage response)
Sync-CsOnlineApplicationInstance: The server responded with a Server Error, Status: InternalServerError

**Comment by ErwinWiegman** [comment]
In the meantime also tried it with 5.4.0. Same issue

**Comment by Namita2015-lab** [comment]
Please help with the internal Server error issue. Facing the same issue following the document - https://learn.microsoft.com/en-us/microsoftteams/teams-recording-policy#compliance-recording-policy-assignment-and-provisioning

Kindly confirm if there are any pre-requisites that need to be met for the application before making this sync call. @Hank-TNguyen

**Comment by ErwinWiegman** [comment]
I first created a resource account in the teams portal. Added a resource account license. Added a phone number. And ran the command.

You can also follow these commands

https://doc.roger365.io/documentation/configuration/contactcenter/resource-accounts/





Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: 123kj45 ***@***.***>
Datum: 22-08-2023 07:17 (GMT+01:00)
Aan: MicrosoftDocs/office-docs-powershell ***@***.***>
Cc: "Erwin Wiegman | ROGER365.io" ***@***.***>, Author ***@***.***>
Onderwerp: Re: [MicrosoftDocs/office-docs-powershell] Sync-CsOnlineApplicationInstance fails with parse error: ParserException/Expected '{' or '['. Was String: (Issue #11175)


Please help with the internal Server error issue. Facing the same issue following the document - https://learn.microsoft.com/en-us/microsoftteams/teams-recording-policy#compliance-recording-policy-assignment-and-provisioning

Kindly confirm if there are any pre-requisites that need to be met for the application before making this sync call. @Hank-TNguyen<https://github.com/Hank-TNguyen>

**Comment by emoshaya** [comment]
@Hank-TNguyen we're facing the same issue here. When we pass in ApplicationId too, we get a slightly different error:

`DEBUG: CmdletProcessRecordAsyncStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /Teams.PlatformService/v2/ApplicationInstances/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/sync?applicationId=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
DEBUG: RequestCreated: /Teams.PlatformService/v2/ApplicationInstances/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/sync?applicationId=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx
DEBUG: HeaderParametersAdded:
DEBUG: SetExecutionId: 94ea359f-902c-4790-ab4c-ac35d0349000
DEBUG: BeforeCall:
DEBUG: ResponseCreated:
DEBUG: Finally:
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: CmdletEndProcessing:
Sync-CsOnlineApplicationInstance: The server responded with an unrecognized response, Status: NoContent`

**Comment by Hank-TNguyen** [comment]
@ErwinWiegman 
`Sync-CsOnlineApplicationInstance -ObjectId c3fa22f1-89f5-4ee9-bc37-041242368e7c -ApplicationId <AppId>`

Can you provide the applicationId as well? I will update the guidance where the appId is missing. Going forward, in future release of the Teams powershell module, this will be a required param. 


@emoshaya
Sorry, this is expected. In the next powershell module release, this problem will be resolved. For now, the sync request has gone through, please disregard this error.

**Comment by get-itips** [comment]
Hello everyone, here we are limited to **documentation** issues and fixes, I think the best in this scenario would be to open a support request from the tenant.
@JensTrier for awareness
