### ISSUE TITLE
Managed Identity issue with Microsoft Arc enrolled physical system.

### ISSUE THREAD

**Issue by eschlueterlpp** [MicrosoftDocs/office-docs-powershell#11440]
**Basic System Info**
Windows Server 2022 Standard
Powershell version 7.3.9
Module version 3.4.0
Ticket opened with Microsoft: Yes, 2311080010003648

**Noted the following supported items:**
Managed identity connections are currently supported for the following types of Azure resources:

Azure Automation runbooks
Azure Virtual Machines
Azure Virtual Machine Scale Sets
Azure Functions
You must use this switch with the Organization parameter.

**Issue**
Managed Identity is not supported yet on ExchangeOnlineManagement module for Microsoft Arc Physical systems with System assigned Managed Identities.

**Command**
 -- Updated Contoso to your tenant domain
Connect-ExchangeOnline -ManagedIdentity -Organization Contoso.onmicrosoft.com

**Error**
Failed to acquire managed identity token:
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (169.254.169.254:80)
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Exchange.Management.AdminApiProvider.Authentication.ManagedIdentityTokenProvider.GetAccessTokenAsync(String claims, String cmdletId)
OperationStopped: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (169.254.169.254:80)

**Comment by chrisda** [comment]
@eschlueterlpp, you should open a support ticket about this. Report back here with any information that can help improve the documentation.

**Comment by eschlueterlpp** [comment]
Thanks Chris, I've opened support ticket 2311080010003648. Will update what they say.
