### ISSUE TITLE
ConvertTo-SPOMigrationTargetedPackage : The number of sub-authorities must not exceed 15

### ISSUE THREAD

**Issue by Mukesh2085** [MicrosoftDocs/office-docs-powershell#2115]
I have a document library in SharePoint 2016 (On-Prem) which has multiple folders and documents within it. Size of library back including all versions go up to 2.5GB and around 831 .dat files are created after backup along with other necessary xml files needed for SharePoint online migration.

While other test library migration was successful, I am receiving below exception while trying to convert source package for SP Online compatible package after executing .

Command:

$convertedPackage = ConvertTo-SPOMigrationTargetedPackage -SourceFilesPath $sourceFiles -SourcePackagePath $sourcePackage -OutputPackagePath $targetPackage -TargetWebUrl $targetWeb  -TargetDocumentLibraryPath $targetDocLib -Credentials $creds

MSDN document for migrating libraries from On-Prem to SP Online: [Migration Article](https://docs.microsoft.com/en-us/sharepointmigration/upload-on-premises-content-to-sharepoint-online-using-powershell-cmdlets)
Exception:

ConvertTo-SPOMigrationTargetedPackage : The number of sub-authorities must not exceed 15 

Let me know if any inputs are needed to answer this issue.

Conversion log:

Adding SystemObject node for List/Document Library '/sites/SiteName/Shared Documents' to prevent import from attempting to create object

Adding SystemObject node for List/Document Library parent folder '/sites/SiteName/Shared Documents' to prevent import from attempting to create object

Error Fatal exception found: The number of sub-authorities must not exceed 15.

Parameter name: binaryForm -  -    at System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm(Byte[] binaryForm, Int32 offset)

   at Microsoft.Online.SharePoint.Migration.Helpers.Trustee.ConvertToDecodedSystemId(String encodedId, AccountType& accountType, String& decodedSid)

   at Microsoft.Online.SharePoint.Migration.Helpers.Trustee.set_SourceEncodedSystemId(String value)

   at Microsoft.Online.SharePoint.Migration.PackageTransformer.UserGroupMap.<Transform>b__2(XElement user)

   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()

   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at Microsoft.Online.SharePoint.Migration.PackageTransformer.UserGroupMap.Transform(MigrationTarget migrationTarget, FileInfo userMappingFileInfo)

   at Microsoft.Online.SharePoint.Migration.PackageTransformer.Package.Transform(MigrationTarget migrationTarget, Dictionary`2 migrationObjects, FileInfo userMappingFileInfo, TargetEnvironment targetEnvrionment, NetworkCredential graphApiUserCredentials)

   at Microsoft.Online.SharePoint.Migration.MigrationPackageConverter.ConvertPackage(DirectoryInfo SourcePackageFilesPath, DirectoryInfo SourcePackageMetadataPath, DirectoryInfo OutputPackageMetadataPath, Uri TargetWebUrl, String TargetListPath, String TargetDocumentLibrarySubFolderPath, TargetEnvironment TargetEnvrionment, FileInfo UserMappingFile, Boolean ListIsDocumentLibrary, Boolean NoAzureADLookup, NetworkCredential AzureADUserCredentials)

11/14/2018 11:47:01 AM Error Fatal exception found: The number of sub-authorities must not exceed 15.

**Comment by tseward** [comment]
Is there a reason you'd use this rather than the SharePoint Migration Tool or a 3rd party migration tool?

**Comment by Mukesh2085** [comment]
@tseward i need to move only one document library, SP migration tool doesn't support migration from SP2016 to SP online. We don't have 3rd party tool license yet.
If i remove the -IncludeSecurity parameter issue goes away.

**Comment by msbemba** [comment]
Sorry about the issue. Since you had only one library to migrate and you have used the workaround, Is this still an issue?

**Comment by msbemba** [comment]
@Mukesh2085 We see from the comments that you had already fixed it using the workaround of including -IncludeSecurity parameter. The next time you have this issue come up we want to make sure it's documented and worked on by support so please open a support ticket.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y
