### ISSUE TITLE
Failed to connect-PnPOnline with UseWebLogin

### ISSUE THREAD

**Issue by azMantas** [MicrosoftDocs/office-docs-powershell#4061]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
   at OfficeDevPnP.Core.AuthenticationManager.<>c__DisplayClass22_0.<GetWebLoginClientContext>b__0()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Win 10
PowerShell Core

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by tseward** [comment]
Use Windows PowerShell. PnP modules require .NET Framework components that are not available in .NET Core (hence PoSh Core).

**Comment by yogkumgit** [comment]
@tseward  Thank you very much for the contribution and sharing this explanation. @azMantas 
Hope this comment is helpful for you. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
