### ISSUE TITLE
Getting errors on Get-Team, Get-TeamChannel, ver 1.0.5 + 1.0.3

### ISSUE THREAD

**Issue by jdamsgaa** [MicrosoftDocs/office-docs-powershell#5326]
The only command I have managed to get working is Get-TeamUser -GroupId ...... the others fail. What am I doing wrong? Have tried it on a Windows 10 system as well as a Windows Server 2016 Standard. Both runnning Powershell 5.1

Get-TeamChannel -GroupId (same GroupId that's working in Get_TeamUser) : 
Code: BadRequest
Message: Failed to execute Skype backend request GetThreadS2SRequest.

Get-Team: 
I can see in the logfile that it actually retrieves the Teams in our tenant (5 teams), but fails in aggregating these (?) Below is an extract from the logfile in AppData:

Error     	Get-Team.ProcessRecord                  	System.AggregateException - One or more errors occurred..    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.Parallel.ArrayMergeHelper`1.Execute()
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
   at Microsoft.TeamsCmdlets.PowerShell.Custom.GetTeam.ProcessRecord()

**Comment by jdamsgaa** [comment]
Suddenly started working by itself - no idea why it didn't work before
