### ISSUE TITLE
Connect-ExchangeOnline triggers >>The term 'Get-Runspace' is not recognized ...<<

### ISSUE THREAD

**Issue by Michal-Ziemba** [MicrosoftDocs/office-docs-powershell#5571]
When executing Connect-ExchangeOnline command from Exchange Online PowerShell V2 module got the error:
CategoryInfo=ObjectNotFound:   (Get-Runspace:String) [] CommandNotFoundException

Module version I am using is 0.4578.0
PowerShell version: 4.0   

```
ExceptionMessage=System.Management.Automation.CommandNotFoundException: The term 'Get-Runspace' is not recognized as the name of a cmdlet function script file or operable program. Check the spelling of the name or if a path was included verify that the path is correct and try again.
  at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext Exception exception)
  at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
  at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
  at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
  at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
  at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke Boolean createLocalScope Dictionary`2 functionsToDefine List`1 variablesToDefine ErrorHandlingBehavior errorHandlingBehavior Object dollarUnder Object input Object scriptThis Pipe outputPipe InvocationInfo invocationInfo Object[] args)
  at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
  at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
  at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope Dictionary`2 functionsToDefine List`1 variablesToDefine ErrorHandlingBehavior errorHandlingBehavior Object dollarUnder Object input Object scriptThis Pipe outputPipe InvocationInfo invocationInfo Object[] args)
  at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder Object input Object[] args)
  at Microsoft.Exchange.Management.ExoPowershellModule.Telemetry.AddEXOClientTelemetryWrapper.AddCleanupHook()
  at Microsoft.Exchange.Management.ExoPowershellModule.Telemetry.AddEXOClientTelemetryWrapper.ProcessRecord()
  at System.Management.Automation.CommandProcessor.ProcessRecord()|
```

**Comment by yogkumgit** [comment]
@officedocsbot assign @yogkumgit

**Comment by dariomws** [comment]
Hi @Michal-Ziemba, thank you for your feedback and help us to improve docs.

As this module is still in preview and it seems that it´s a particular issue in your environment I need to suggest you that follow these steps to report it:
https://docs.microsoft.com/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2#report-bugs-and-issues

**Comment by yogkumgit** [comment]
@dariomws  Thank you very much for the contribution and sharing this explanation. @Michal-Ziemba Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
