### ISSUE TITLE
Get-CsUserCallingSettings gives error to console and error stream for Online Application Instances

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#8643]
Teams Online PowerShell module, version 2.6.2-Preview
on Windows Server 2019, build 17763.2114
running PS Desktop, version 5.1.17763.2090.

If you run Get-CsUserCallingSettings and provide the FQDN of a phone enabled Online Application Instance, you get errors.
I have not tested with a non-telephony-enabled application instance.

When I run
Get-CsUserCallingSettings -Identity UPN

I get this result; the first part is returned to the console; The  the rest is provided to the error stream):
_(I replaced the user's UPN with "UPN")_

```
ParserException/Expected '{' or '['. Was String: Entity./   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonParser.ReadNode()
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(String text)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.RestException..ctor(HttpResponseMessage response)
Get-CsUserCallingSettings : The server responded with a Request Error, Status: NotFound
At line:1 char:1
+get-csusercallingsettings -Identity UPN. ...
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    +CategoryInfo          : InvalidOperation: ({ Identity = UPN }:<>f__AnonymousType5`1) [Get-CsUserCallingSett
   ings_Get], UndeclaredResponseException
    +FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsUserCallingSettings_Get
```

If I run the command with -debug enabled and accept all executions, I get to this (where I replaced the user's UPN with "UPN"):

```
PS > Get-CsUserCallingSettings -Identity UPN -Debug
DEBUG: CmdletBeginProcessing:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: CmdletProcessRecordStart:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: CmdletProcessRecordAsyncStart:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: CmdletGetPipeline:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: CmdletBeforeAPICall:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: URLCreated: /Skype.VoiceGroup/userRoutingSettings/UPN

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: RequestCreated: /Skype.VoiceGroup/userRoutingSettings/UPN

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: HeaderParametersAdded:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: BeforeCall:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: ResponseCreated:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
ParserException/Expected '{' or '['. Was String: Entity./   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonParser.ReadNode()
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.Json.JsonNode.Parse(String text)
   at Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Runtime.RestException..ctor(HttpResponseMessage response)
DEBUG: Finally:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):

Confirm
The server responded with a Request Error, Status: NotFound
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
Get-CsUserCallingSettings : The server responded with a Request Error, Status: NotFound
At line:1 char:1
+ Get-CsUserCallingSettings -Identity UPN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = UPN }:<>f__AnonymousType5`1) [Get-CsUserCallingSettings_Get], UndeclaredResponseException
    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsUserCallingSettings_Get
DEBUG: CmdletProcessRecordAsyncEnd:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: CmdletProcessRecordEnd:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
DEBUG: CmdletEndProcessing:

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"):
```

**Comment by dariomws** [comment]
Hi @donlassini, thank you for your feedback.

This cmdlet is currently in public preview and I understand you can run it to get settings for standard users, not for Online Application Instances.
Anyway, if you want to double-check, please try the latest preview version for the Teams PowerShell module:
https://www.powershellgallery.com/packages/MicrosoftTeams/3.0.1-preview

**Comment by yogkumgit** [comment]
@dariomws Thank you very much for the contribution and sharing this explanation. @donlassini Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
