### ISSUE TITLE
Get-CsOnlineUser and Set-CsUser does not handle exceptions correctly in some cases

### ISSUE THREAD

**Issue by donlassini** [MicrosoftDocs/office-docs-powershell#9103]
Using Teams Online PowerShell module, version 4.0.0 in Windows PowerShell 5.1:

Try running this **in a new PowerShell session** - and write it literally (i.e. do not substitute "x" with anything else, and do not connect prior to running the command):
```
PS> Try {Get-CsOnlineUser -Identity "x" -ErrorAction Stop} Catch {Write-Host "Caught"}
Caught
```
The error will be thrown as an exception that you catch.

Then try this:
```
PS> Connect-MicrosoftTeams
PS> Try {Get-CsOnlineUser -Identity "x" -ErrorAction Stop} Catch {Write-Host "Caught"}
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsUser : userId was not found
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.0.0\net472\custom\PsExt\Merged_custom_PsExt.ps1:1836 char:13
+             $user = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-Cs ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = x,...et = Extended }:<>f__AnonymousType58`7) [Get-CsUser_Get], Exception
    + FullyQualifiedErrorId : NotFound,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsUser_Get
```
You will get error data back, even if you asked for errors to be handles as exceptions, and exceptions caught:

Finally try this:
```
PS> Connect-MicrosoftTeams
PS> Get-Module microsoftteams|Remove-Module;Import-Module microsoftteams
PS> Try {Get-CsOnlineUser -Identity "x" -ErrorAction Stop} Catch {Write-Host "Caught"}
Caught
```
That is actually a workaround(!)
So I think there's a dependency issue when you import the Teams Online module.

Same thing goes with Set-CsUser.

**Comment by DEberhardt** [comment]
As far as I could determine, this is a back-end issue. the error is thrown by an internal function:

```powershell
+ CategoryInfo          : InvalidOperation: ({ Identity = x,...et = Extended }:<>f__AnonymousType58`7) [Get-CsUser_Get], Exception
```

I belive there is a typo in the Name of the `f__AnonymousType` variable and the apostrophe is breaking that comparison. The Cmdlet `Get-csUser_Get` does not adhere to the `ErrorAction` at all. Have noticed this across multiple cmdlets that now throw errors and had opened a ticket a few weeks ago (still pending)

@isrumnon Has this crossed your radar yet?

**Comment by isrumnon** [comment]
@DEberhardt not yet, we'll look into this. Thanks for bringing this up

**Comment by DEberhardt** [comment]
found a few more examples:
```powershell
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Search-CsUser : AADGraph Request failed with BadRequest. AAD Code  Message . 
Parameter name: https://graph.windows.net/f66fae02-5d36-495b-bfe0-78a6ff9f8e6e/users?api-version=1.61-internal&$select= 
assignedPlans,cloudMSRtcIsSipEnabled,preferredLanguage,shadowProxyAddresses,displayName,jobTitle,givenName,surname,acco 
untEnabled,streetAddress,cloudSipLine,cloudSipProxyAddress,state,userPrincipalName,proxyAddresses,objectId,usageLocatio 
n,dirSyncEnabled,UserType,country,department,provisionedPlans,cloudMSRtcOwnerUrn,tenantId,cloudMSRtcServiceAttributes,c 
loudMSRtcPolicyAssignments,mailNickname,companyName,postalCode,city&$top=100&$filter=(contains(cloudSipLine,            
%27tel%3a%2b862122128153%27))                                                                                           
At \Documents\WindowsPowerShell\Modules\MicrosoftTeams\3.1.0\net472\custom\PsExt\Get-CsUserSearch.ps1:52 char:13        
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Search-CsUser  ...                                             
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 
    + CategoryInfo          : InvalidOperation: ({ PageSize = , ...olicy = False }:<>f__AnonymousType73`9) [Search-CsU  
    ser_Search], Exception                                                                                              
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SearchCsUser_Search       
    Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : User does not exist                                 
    At \Documents\WindowsPowerShell\Modules\MicrosoftTeams\3.1.0\net472\custom\PsExt\Grant-CsUserOrTenantPolicy.ps1:61  
    char:13                                                                                                             
    +             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPo ...                                         
    +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                             
    + CategoryInfo          : InvalidOperation: ({ Identity = Ho...ntUserRequest }:<>f__AnonymousType55`3) [Grant-CsUs  
    erPolicy_GrantExpanded], Exception                                                                                  
    + FullyQualifiedErrorId : ClientError,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GrantCsUserPolicy_GrantE  
    xpanded                                                                                                             
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGenerated : 862122128152 is assigned to another user              
 At \Documents\WindowsPowerShell\Modules\MicrosoftTeams\3.1.0\net472\custom\PsExt\Set-CsUserModern.ps1:51 char:13       
 +             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Set-CsUserGene ...                                            
 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                
 + CategoryInfo          : InvalidOperation: ({ UserId = sip:...onaryOfString }:<>f__AnonymousType86`2) [Set-CsUser    
 Generated_Set], Exception                                                                                               
 + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SetCsUserGenerated_Set


```

**Comment by DEberhardt** [comment]
Found another one when running the following commands:
```powershell
$Filter = 'LineURI -like "*{0}*"' -f "12345678901234"
Get-CsOnlineUser -Filter $Filter

Microsoft.Teams.ConfigAPI.Cmdlets.internal\Search-CsUser : AADGraph Request failed with BadRequest. AAD Code  Message .
Parameter name: https://graph.windows.net/f66fae05-5d36-495b-bfa0-78a6ff9a8e6e/users?api-version=1.61-internal&$select=
assignedPlans,cloudMSRtcIsSipEnabled,preferredLanguage,shadowProxyAddresses,displayName,jobTitle,givenName,surname,acco
untEnabled,streetAddress,cloudSipLine,cloudSipProxyAddress,state,userPrincipalName,proxyAddresses,objectId,usageLocatio
n,dirSyncEnabled,UserType,country,department,provisionedPlans,cloudMSRtcOwnerUrn,tenantId,cloudMSRtcServiceAttributes,c
loudMSRtcPolicyAssignments,mailNickname,companyName,postalCode,city&$top=100&$filter=(contains(cloudSipLine,
%27tel%3a%2b862122128202%27))
At \Documents\WindowsPowerShell\Modules\MicrosoftTeams\4.0.0\net472\custom\PsExt\Merged_custom_PsExt.ps1:1941 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Search-CsUser  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ PageSize = , ...et = Extended }:<>f__AnonymousType80`11) [Search-Cs
   User_Search], Exception
    + FullyQualifiedErrorId : BadArgument,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SearchCsUser_Search

```

This is on v4 btw.

Filter works for `"Userprincipalname -eq '...'"` but not for `"LineUri -like..."`

Does MicrosoftTeams now require a connection to AADGraph or is this message misleading me?

**Comment by DEberhardt** [comment]
It looks like the * at the beginning is creating issues here:
```powershell
❯ Get-CsOnlineUser -Filter {LineURI -like '123456789*'} -ResultSize 1


AccountEnabled                         : True
...
#This returns a result

❯ Get-CsOnlineUser -Filter {LineURI -like '*234567890'} -ResultSize 1
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Search-CsUser : Specified method is not supported.
At C:\Users\david.eberhardt\OneDrive - Applicable
Ltd\Documents\WindowsPowerShell\Modules\MicrosoftTeams\4.0.0\net472\custom\PsExt\Merged_custom_PsExt.ps1:1941 char:13
+             Microsoft.Teams.ConfigAPI.Cmdlets.internal\Search-CsUser  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ PageSize = , ...et = Extended }:<>f__AnonymousType80`11) [Search-Cs
   User_Search], Exception
    + FullyQualifiedErrorId : FeatureNotSupported,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.SearchCsUser_Sea
   rch
#This does not

#using wildcards at the beginning & end results in the error above
```

**Comment by DEberhardt** [comment]
> notice that Get-CsOnlineUser actually generates a proper exception as expected if you remove and import the module after connecting to Teams (last part of my original description).

I just tried this now and indeed the search behaves differently.

```powershell
❯ Get-CsOnlineUser -Filter {LineURI -like '*234567890'} -ResultSize 1
# no result - this should have been giving me a result

❯ Get-CsOnlineUser -Filter {LineURI -like '123456789*'} -ResultSize 1
# no result - this is correct as the LineURI starts with 'tel:+'

❯ Get-CsOnlineUser -Filter {LineURI -like 'tel:+1203816310*'} -ResultSize 1


UserAccountControl                     : PasswordNotRequired, NormalAccount
...
# User object returned

❯ Get-CsOnlineUser -Filter {LineURI -like '*234567890*'} -ResultSize 1


UserAccountControl                     : PasswordNotRequired, NormalAccount
...
# User object returned
```

**Comment by donlassini** [comment]
@DEberhardt , this issue is not about the filter not working as expected, it's about the cmdlet not throwing exceptions properly and adhering to the -erroraction parameter.
So regarding this issue, I don't think that any of your comments are relevant. Yes, they are relevant but for a totally different bug.

**Comment by poshdude** [comment]
Have noticed this too for other commands with 4.0.0
e.g.
```
Try {
    Grant-CsTenantDialPlan -Identity <UPN> -PolicyName "Idontexist" -ErrorAction Stop
}
Catch {
    Write-Host "Handling ex"
}
```
The exception is seen on screen and not caught
```
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : "Idontexist" not found
.....
```
But it is in the error stream
```
$error[0]
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : "Idontexist" not found
.....
```
And also not sent to an error variable, e.g. this doesn't work either
```
Grant-CsTenantDialPlan -Identity <UPN> -PolicyName "Idontexist" -ErrorVariable errtdp
Write-Host $errtdp
```

The workaround posted by @donlassini works so possibly something related to the auto-loading of the MicrosoftTeams module rather than explicitly loading it?

**Comment by poshdude** [comment]
Small update to above...

Reloading the MT modules works for Try Catch but sending to an error variable results in a new exception

```
Grant-CsTenantDialPlan -Identity <UPN> -PolicyName "Idontexist" -ErrorVariable errtdp

Grant-CsTenantDialPlan : A variable that cannot be referenced in restricted language mode or a Data section is being referenced. Variables that can
be referenced include the following: $PSCulture, $PSUICulture, $true, $false, $null.
.....
```

**Comment by donlassini** [comment]
@poshdude, I just tested, and it's not related to autoimporting the module FYI.
Your observations around the error variables are great! I can produce the same results.

**Comment by poshdude** [comment]
@donlassini  - thanks for that.  Do you notice that re-importing the module as you suggested reverts back to (now) legacy PSRemoting session for MicrosoftTeams?

e.g. if you run Get-PSSession

```
Get-PSSession

 Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  1 SfBPowerShel... api.interfac... RemoteMachine   Opened        Microsoft.PowerShell     Available
```

and you start seeing legacy properties i.e. as I noted above about the Identity property....

**Comment by donlassini** [comment]
@poshdude - another great observation :-)
I examined it, and noticed that that session is not shown until after you run a command, e.g. Get-CsOnlineUser. If you just reimport the module and do nothing, Get-PsSession will give you nothing. I tried waiting for 2 minutes just in case.

**Comment by poshdude** [comment]
@donlassini  - no worries.  I guess just be aware that the connection changes to legacy and the properties returned by commands may not match the properties we are now expecting in the modern v.4.x module.  Incidentally, this seems to work for me without the need to remove and reload the module, so perhaps a better option here for now?

```
Try {
     Grant-CsTenantDialPlan -Identity <UPN> -PolicyName "Idontexist" -PassThru -ErrorAction Stop | Out-Null
}
Catch {
     Write-Host "Handling ex"
}

Try {
     Grant-CsTenantDialPlan -Identity <UPN> -PolicyName <A policy that does exist> -PassThru -ErrorAction Stop | Out-Null
}
Catch {
     Write-Host "Handling ex"
}
```

**Comment by DEberhardt** [comment]
This is tangential, but many CmdLets have been migrated to the AutoRest API now - these do not create a session when called. AFAIK there is no (published) documentation on which CmdLets are behaving a certain way.
From what I could ascertain, the PSSession is now created silently and in the background. It is also cycled automatically.

I am using `Get-CsTenant` to validate at the moment, as the Command is not using AutoRest

```powershell
❯ Get-PSsession

 Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  3 SfBPowerShel... api.interfac... RemoteMachine   Broken        Microsoft.PowerShell          None
 13 SfBPowerShel... api.interfac... RemoteMachine   Broken        Microsoft.PowerShell          None

❯$Tenant = Get-CsTenant -WarningAction SilentlyContinue -ErrorAction Stop -Verbose
VERBOSE: EnabledForFlight: False, AutoRestCommandInfo: False
VERBOSE: Correlation Id: 1bb4f5cb-b692-437f-a3f1-a37551ed95e5
❯if ( $Tenant ) { return $true } else { return $false }
True

❯ Get-PSsession

 Id Name            ComputerName    ComputerType    State         ConfigurationName     Availability
 -- ----            ------------    ------------    -----         -----------------     ------------
  3 SfBPowerShel... api.interfac... RemoteMachine   Broken        Microsoft.PowerShell          None
 15 SfBPowerShel... api.interfac... RemoteMachine   Opened        Microsoft.PowerShell     Available

```

**Comment by poshdude** [comment]
IMHO, the PS Remoting  appears to be central to the issue.   We see above that commands that utilise PS Remoting work as expected for exception handling (Try, Catch).  By utilising the Verbose switch as above we can see this behaviour.

```
# Remove any existing PS Session
Get-PSSession | Remove-PSSession

# Lets have some properties where we can observe legacy vs new values
$csolProps = @(
    'Identity',
    'ObjectId',
    'LineURI',
    'OnPremLineURI',
    'OnPremLineUriManuallySet',
    'FeatureTypes'
)

# Run a command with verbose (AutoRest)
Get-CsOnlineUser -Identity <UPN> -Verbose | Select $csolProps
VERBOSE: EnabledForFlight: True, AutoRestCommandInfo: True

Identity                 : fb3491a9-xxxx-xxxx-xxxx-9a4424ca9c89
ObjectId                 :
LineUri                  : tel:+44xxxxxxxx
OnPremLineUri            : tel:+44xxxxxxxx
OnPremLineUriManuallySet :
FeatureTypes             : {AudioConferencing, Teams, PhoneSystem}

# Run a command that should generate an exception we can catch (AutoRest)
Try {
     Grant-CsTenantDialPlan -Identity mohammad.jameel@applicable.com -PolicyName "Idontexist" -ErrorAction Stop -Verbose
}
Catch {
     Write-Host "Handling ex"
}
VERBOSE: EnabledForFlight: True, AutoRestCommandInfo: True
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Grant-CsUserPolicy : "Idontexist" not found
.....
#Exception not caught using AutoRest

# Run the same command with -PassThru (no AutoRest)
Try {
     Grant-CsTenantDialPlan -Identity mohammad.jameel@applicable.com -PolicyName "Idontexist" -PassThru -ErrorAction Stop -Verbose | Out-Null
}
Catch {
     Write-Host "Handling ex"
}
VERBOSE: EnabledForFlight: False, AutoRestCommandInfo: False
.....
Handling ex
#Exception caught

# If we run the previous command again (AutoRest)
Get-CsOnlineUser -Identity <UPN> -Verbose | Select $csolProps
VERBOSE: EnabledForFlight: True, AutoRestCommandInfo: True

Identity                 : fb3491a9-xxxx-xxxx-xxxx-9a4424ca9c89
ObjectId                 :
LineUri                  : tel:+44xxxxxxxx
OnPremLineUri            : tel:+44xxxxxxxx
OnPremLineUriManuallySet :
FeatureTypes             : {AudioConferencing, Teams, PhoneSystem}

# clear PSSession and re-import the MT module
Get-PSSession | Remove-PSSession
Get-Module MicrosoftTeams | Remove-Module
Import-Module MicrosoftTeams

# now run the previous command again ( no AutoRest)
Get-CsOnlineUser -Identity <UPN> -Verbose | Select $csolProps
VERBOSE: EnabledForFlight: False, AutoRestCommandInfo: False
VERBOSE: Correlation Id: d4c8a5d2-9b58-4a2e-9a83-5cecb03dd51e

Identity                 : CN=fb3491a9-xxxx-xxxx-xxxx-9a4424ca9c89,OU=xxxxxxxxxxxxxxxxxx,OU=OCS Tenants,DC=lync0a001,DC=local
ObjectId                 : fb3491a9-xxxx-xxxx-xxxx-9a4424ca9c89
LineUri                  : tel:+44xxxxxxxx
OnPremLineUri            : tel:+44xxxxxxxx
OnPremLineURIManuallySet : False
FeatureTypes             :

# now we also see legacy property values
```
Re-importing the module seems to globally set all commands to not use AutoRest,  great for exception handling, but does affect the property values being returned which why I mentioned about your mileage varying.

**Comment by poshdude** [comment]
Hi,

Looks good from policies perspective.

```
# cycle through available grant policy commands and catch exception
$x = foreach ($cmd in  (Get-Module MicrosoftTeams | Select -ExpandProperty ExportedCommands).Keys) {
    If ($cmd -match 'Grant-Cs\w+Policy') {
        $r = @{}
        $r.Command = $cmd
        Try {
            & $cmd -PolicyName "Idont exist" -Identity <UPN> -ErrorAction Stop
            $r.Exception = $null
        }
        catch {
            $r.Exception = ([string]$_ -split "At line")[0]
        }
        [pscustomobject]$r
    }
}
 
$x | Format-Table -Autosize
```

**4.0.1**
```
Command                                      Exception
-------                                      ---------
Grant-CsApplicationAccessPolicy              [ClientError] : "Idont exist" not found
Grant-CsBroadcastMeetingPolicy               Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsClientPolicy                         Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsCloudMeetingPolicy                   Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsConferencingPolicy                   Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsDialoutPolicy                        [ClientError] : "Idont exist" not found
Grant-CsExternalAccessPolicy                 [ClientError] : "Idont exist" not found
Grant-CsExternalUserCommunicationPolicy      Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsGraphPolicy                          Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsGroupPolicyPackageAssignment         A parameter cannot be found that matches parameter name 'PolicyName'.
Grant-CsHostedVoicemailPolicy                Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsIPPhonePolicy                        Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsMobilityPolicy                       Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsOnlineAudioConferencingRoutingPolicy [ClientError] : "Idont exist" not found
Grant-CsOnlineVoicemailPolicy                [ClientError] : "Idont exist" not found
Grant-CsOnlineVoiceRoutingPolicy             Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsTeamsAppPermissionPolicy             [ClientError] : "Idont exist" not found
Grant-CsTeamsAppSetupPolicy                  [ClientError] : "Idont exist" not found
Grant-CsTeamsAudioConferencingPolicy         [ClientError] : "Idont exist" not found
Grant-CsTeamsCallHoldPolicy                  [ClientError] : "Idont exist" not found
Grant-CsTeamsCallingPolicy                   [ClientError] : "Idont exist" not found
Grant-CsTeamsCallParkPolicy                  [ClientError] : "Idont exist" not found
Grant-CsTeamsChannelsPolicy                  [ClientError] : "Idont exist" not found
Grant-CsTeamsComplianceRecordingPolicy       [ClientError] : "Idont exist" not found
Grant-CsTeamsCortanaPolicy                   [ClientError] : "Idont exist" not found
Grant-CsTeamsEmergencyCallingPolicy          [ClientError] : "Idont exist" not found
Grant-CsTeamsEmergencyCallRoutingPolicy      [ClientError] : "Idont exist" not found
Grant-CsTeamsEnhancedEncryptionPolicy        [ClientError] : "Idont exist" not found
Grant-CsTeamsFeedbackPolicy                  [ClientError] : "Idont exist" not found
Grant-CsTeamsFilesPolicy                     [ClientError] : "Idont exist" not found
Grant-CsTeamsIPPhonePolicy                   [ClientError] : "Idont exist" not found
Grant-CsTeamsMeetingBroadcastPolicy          [ClientError] : "Idont exist" not found
Grant-CsTeamsMeetingPolicy                   [ClientError] : "Idont exist" not found
Grant-CsTeamsMessagingPolicy                 [ClientError] : "Idont exist" not found
Grant-CsTeamsMobilityPolicy                  [ClientError] : "Idont exist" not found
Grant-CsTeamsShiftsPolicy                    [ClientError] : "Idont exist" not found
Grant-CsTeamsSurvivableBranchAppliancePolicy [ClientError] : "Idont exist" not found
Grant-CsTeamsUpdateManagementPolicy          [ClientError] : "Idont exist" not found
Grant-CsTeamsUpgradePolicy                   [ClientError] : "Idont exist" not found
Grant-CsTeamsVdiPolicy                       [ClientError] : "Idont exist" not found
Grant-CsTeamsVideoInteropServicePolicy       [ClientError] : "Idont exist" not found
Grant-CsTeamsWorkLoadPolicy                  [ClientError] : "Idont exist" not found
Grant-CsUserPolicyPackage                    A parameter cannot be found that matches parameter name 'PolicyName'.
Grant-CsVoiceRoutingPolicy                   Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
```
**4.0.0**
```
A sea of red....

Command                                      Exception
-------                                      ---------
Grant-CsApplicationAccessPolicy
Grant-CsBroadcastMeetingPolicy               Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsClientPolicy                         Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsCloudMeetingPolicy                   Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsConferencingPolicy                   Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsDialoutPolicy
Grant-CsExternalAccessPolicy
Grant-CsExternalUserCommunicationPolicy      Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsGraphPolicy                          Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsGroupPolicyPackageAssignment         A parameter cannot be found that matches parameter name 'PolicyName'.
Grant-CsHostedVoicemailPolicy                Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsIPPhonePolicy                        Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsMobilityPolicy                       Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsOnlineAudioConferencingRoutingPolicy
Grant-CsOnlineVoicemailPolicy
Grant-CsOnlineVoiceRoutingPolicy             Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
Grant-CsTeamsAppPermissionPolicy
Grant-CsTeamsAppSetupPolicy
Grant-CsTeamsAudioConferencingPolicy
Grant-CsTeamsCallHoldPolicy
Grant-CsTeamsCallingPolicy
Grant-CsTeamsCallParkPolicy
Grant-CsTeamsChannelsPolicy
Grant-CsTeamsComplianceRecordingPolicy
Grant-CsTeamsCortanaPolicy
Grant-CsTeamsEmergencyCallingPolicy
Grant-CsTeamsEmergencyCallRoutingPolicy
Grant-CsTeamsEnhancedEncryptionPolicy
Grant-CsTeamsFeedbackPolicy
Grant-CsTeamsFilesPolicy
Grant-CsTeamsIPPhonePolicy
Grant-CsTeamsMeetingBroadcastPolicy
Grant-CsTeamsMeetingPolicy
Grant-CsTeamsMessagingPolicy
Grant-CsTeamsMobilityPolicy
Grant-CsTeamsShiftsPolicy
Grant-CsTeamsSurvivableBranchAppliancePolicy
Grant-CsTeamsUpdateManagementPolicy
Grant-CsTeamsUpgradePolicy
Grant-CsTeamsVdiPolicy
Grant-CsTeamsVideoInteropServicePolicy
Grant-CsTeamsWorkLoadPolicy
Grant-CsUserPolicyPackage                    A parameter cannot be found that matches parameter name 'PolicyName'.
Grant-CsVoiceRoutingPolicy                   Policy "Idont exist" is not a user policy. You can assign only a user policy to a specific user.
```

Error variable checks out too

```
Grant-CsTenantDialPlan -Identity <UPN> -PolicyName "Idontexist" -ErrorVariable errtdp
Grant-CsTenantDialPlan : [ClientError] : "Idontexist" not found
At line:1 char:1
+ Grant-CsTenantDialPlan -Identity <UPN> -Poli ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Grant-CsTenantDialPlan], Exception
    + FullyQualifiedErrorId : System.Exception,Microsoft.Teams.ConfigApi.Cmdlets.GrantCsTenantDialPlan

Write-Host $errtdp
System.Management.Automation.CmdletInvocationException: [ClientError] : "Idontexist" not found ---> System.Exception: [ClientError] : "Idontexist" not found
   at Microsoft.Teams.ConfigApi.Cmdlets.PowershellUtils.ThrowOnErrors(PowerShell powershell)
   at Microsoft.Teams.ConfigApi.Cmdlets.SyncProcessor.ReceiveOutput()
   at Microsoft.Teams.ConfigApi.Cmdlets.TrpsPSCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options) [ClientError] : "Idontexist" not found [ClientError] : "Idontexist" not found [ClientError] : "Idontexist" not found
```

**Comment by poshdude** [comment]
One last behaviour to query... the commands are now throwing terminating errors i.e. the error can be trapped without specifying -ErrorAction Stop

```
Try {
     Grant-CsTenantDialPlan -Identity <UPN> -PolicyName "Idontexist"
}
Catch {
     Write-Host "Handling ex"
}
Handling ex
```
Is this correct? I would expect to use -ErrorAction Stop if I wanted to catch the error or be able to show the error on console and continue running my script. Thanks.
Is this correct?

**Comment by donlassini** [comment]
It does not work for Set-CsPhoneNumberAssignment. I will report that as a new bug since it behaves differently.
But for the curious people, here's my result:

```
[string]$AlreadyAssignedNumber = "+11111111"
PS> Try {Set-CsPhoneNumberAssignment -Identity $UPN -PhoneNumber $AlreadyAssignedNumber -PhoneNumberType "DirectRouting" -ErrorAction Stop} Catch {Write-Host "Caught!"}

Code       Message
----       -------
BadRequest Telephone Number '+11111111' has already been assigned to another user
```

@poshdude , I'd say the normal thing to do is for the cmdlet itself to decide if the error is critical enough to be thrown as an exception, or if it's enough to write it to the error stream. I do not know exactly what the developers want, but if we at least can override that action with -ErrorAction, then I'm happy :-)

**Comment by poshdude** [comment]
@donlassini - Set-CsPhoneNumberAssigment command does behave differently by design, its not a bug is my understanding - see Description here [https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/teams/teams-ps/teams/Set-CsPhoneNumberAssignment.md](url).  

Agreed on the exception front, just wanting confirmation that it is indeed by design and not an oversight so that I know how to manage bubbling up the exceptions from these commands.

Best Regards

**Comment by donlassini** [comment]
@poshdude , thank you for that. I've closed my ticket then :-)
Not a consistent way of doing it but at least it's documented.
