### ISSUE TITLE
Enable-OrganizationCustomization command gives the same error in multiple tenants

### ISSUE THREAD

**Issue by petersonal2** [MicrosoftDocs/office-docs-powershell#9228]
Enable-OrganizationCustomization command gives the same error in multiple tenants. There is a misstype or some error in the underlying powershell command.
The following error was generated when

```powershell
          if (!$AdvancedHydrateableObjectsSharedEnabled)
          {
            $unifiedRAP = ($NewServicePlanSettings -eq $null -and -not $ServicePlanSettings.Organization.PerMBXPlanRoleAssignmentPolicyEnabled) -or ($NewS
ervicePlanSettings -ne $null -and -not $NewServicePlanSettings.Organization.PerMBXPlanRoleAssignmentPolicyEnabled);
            $raPolicyName = [Microsoft.Exchange.Data.Directory.SystemConfiguration.RoleAssignmentPolicy]::DefaultRoleAssignmentPolicyName;
            $policyDescription = [Microsoft.Exchange.Data.Directory.SystemConfiguration.RoleAssignmentPolicy]::PrecannedRoleAssignmentPolicyDescription;
            $raPolicy = $null;
            Write-ExchangeSetupLog -info ("PerMBXPlanRoleAssignmentPolicyEnabled Task; unifiedRAP=" + $unifiedRAP);
            if($unifiedRAP)
            {
              #Trying to find local RAP object with default name
              $raPolicy = Get-RoleAssignmentPolicy -DomainController $RoleDomainController -Organization $RoleOrganizationHierarchicalPath -IgnoreDehydrat
edFlag | Where {$_.Name -eq $raPolicyName};
              Write-ExchangeSetupLog -info ("PerMBXPlanRoleAssignmentPolicyEnabled Task; raPolicyFound=" + ($raPolicy -ne $null));
            }
            if($unifiedRAP)
            {
              if($raPolicy -eq $null)
              {
                  Write-ExchangeSetupLog -info ("Creating Default RAP " + $raPolicyName);
                  $raPolicy = New-RoleAssignmentPolicy `
                      -Name $raPolicyName `
                      -DomainController $RoleDomainController `
                      -Description $policyDescription `
                      -IsDefault `
                      -IgnoreDehydratedFlag `
                      -Organization $RoleOrganizationHierarchicalPath;
              }
            }
            Write-ExchangeSetupLog -info ("PerMBXPlanRoleAssignmentPolicyEnabled Task; looping through mailboxplans:" + $ServicePlanSettings.MailboxPlans.
Count);
            foreach ($mp in $ServicePlanSettings.MailboxPlans)
            {
                if($mp.Instance -eq $null)
                {
                  Write-ExchangeSetupLog -error ($mp.Name + " MailboxPlan instance value is not set");
                }
                #MailboxPlan has non-null RoleAssignmentPolicy property only if RAP link is stamped explicitly - no implicit default there
                if($mp.Instance.RoleAssignmentPolicy -ne $null -and $unifiedRAP)
                {
                  Write-ExchangeSetupLog -info ("MailboxPlan already with RAP " + $mp.Name);
                  continue;
                }
                if(!$unifiedRAP)
                {
                  $raPolicyName = "RoleAssignmentPolicy-" + $mp.Name;
                  $raPolicy = Get-RoleAssignmentPolicy -DomainController $RoleDomainController -Organization $RoleOrganizationHierarchicalPath -IgnoreDehy
dratedFlag | Where {$_.Name -eq $raPolicyName};
                  if($raPolicy -eq $null)
                  {
                      Write-ExchangeSetupLog -info ("Creating RAP for " + $mp.Name);
                      $raPolicy = New-RoleAssignmentPolicy -Name $raPolicyName -DomainController $RoleDomainController -Description $policyDescription -Or
ganization $RoleOrganizationHierarchicalPath -IgnoreDehydratedFlag;
                  }
                }
                Set-MailboxPlan -Identity $mp.Instance.Identity -RoleAssignmentPolicy $raPolicy.Identity -DomainController $RoleDomainController;
            }
          }
```

was run:

```powershell
System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPr
eference" or common parameter is set to Stop: The role assignment policy"Default Role Assignment Policy" wasn't found. Make sure that you typed the identi
ty correctly.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Microsoft.Exchange.Configuration.MonadDataProvider.MonadPipelineProxy.ClosePipeline(MonadAsyncResult asyncResult)".
    + CategoryInfo          : NotSpecified: (:) [Enable-OrganizationCustomization], ScriptExecutionException
    + FullyQualifiedErrorId : [Server=AM8P194MB1564,RequestId=9f9c49e5-5118-426c-b64a-75bf2574ca64,TimeStamp=2022. 04. 05. 13:07:02] [FailureCategory=Cmd 
   let-ScriptExecutionException] B01DA0E3,Microsoft.Exchange.Management.Deployment.EnableOrganizationCustomizationTask
    + PSComputerName        : outlook.office365.com
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466381e5-1636-1123-8934-8724b9d5610a
* Version Independent ID: cb675317-fcf7-e6bb-0b65-498d0c74db80
* Content: [Enable-OrganizationCustomization (ExchangePowerShell)](https://docs.microsoft.com/en-us/powershell/module/exchange/enable-organizationcustomization?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Enable-OrganizationCustomization.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Enable-OrganizationCustomization.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@petersonal2, it was my understanding that the indicator of whether or not a tenant has been hydrated (the Enable-OrganizationCustomization cmdlet has already been used) is the IsDehydrated property from Get-OrganizationConfig.

I didn't see that anywhere in your script?

**Comment by petersonal2** [comment]
Our company gives IT solutions, and I am turning (trying...) audit log on in Exchange online in multiple copanys. First I do a command (Get-OrganizationConfig).IsDehydrated IF need I do turn on org. customization using Enable-OrganizationCustomization -Confirm:$false . This is all I do. Nothing else. That's when I getting the error. All the error, all the script not mine. I am getting this as a result back.

**Comment by yogkumgit** [comment]
@petersonal2 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
