### ISSUE TITLE
Problems running Compliance Center commands through ExchangeOnlineManagement 2.0.6-Preview6 module

### ISSUE THREAD

**Issue by jhosefer** [MicrosoftDocs/office-docs-powershell#9391]
First, I would like to inform you that the problems reported here only happen when the connection with the IPPSSession is established in the context of an Azure application with authentication via certificate.

How to reproduce:
1) Create an application in Azure AD as per the documentation:  https://docs.microsoft.com/en-us/powershell/exchange/app-only-auth-powershell-v2?view=exchange-ps

2) connect to compliance center: 
Connect-IPPSSession -CertificateThumbprint $CERT_THUMBPRINT -AppId $APP_ID -Organization "$TENANT_NAME.onmicrosoft.com"
(WARNING: Your connection has been redirected to the following URI: "https://bra01b.ps.compliance.protection.outlook.com/Powershell-LiveId?BasicAuthToOAuthConversion=true;PSVersion=7.2.3")

3) Try creating a retention policy:
 New-RetentionCompliancePolicy -Name "Teste Policy 30" -Comment "Teste Policy Description" -OneDriveLocation  $MyLocation -Enabled $false

4) Result:
WARNING: An unexpected error has occurred and a Watson dump is being generated: Exception of type 'Microsoft.Office.Audit.Schema.ExpectedValueException' was thrown.
New-RetentionCompliancePolicy: Exception of type 'Microsoft.Office.Audit.Schema.ExpectedValueException' was thrown.

5) Details:
SerializedRemoteException      : Microsoft.Office.Audit.Schema.ExpectedValueException: Exception of type 'Microsoft.Office.Audit.Schema.ExpectedValueException' was thrown.
                                    at Microsoft.Office.Audit.Schema.BaseAuditRecord.Validate()
                                    at Microsoft.Office.Audit.Schema.AuditRecord.Validate()
                                    at Microsoft.Office.Audit.Schema.RecordSerializer.Write(BaseAuditRecord record)
                                    at Microsoft.Exchange.Data.Storage.Auditing.EopAuditLogger.ConvertAuditRecord(AuditRecord record, LogRowFormatter& logRowFormatter)
                                    at Microsoft.Exchange.Data.Storage.Auditing.EopAuditLogger.WriteAuditRecord(AuditRecord record)
                                    at Microsoft.Office.CompliancePolicy.Tasks.UnifiedPolicyAuditLogger.WriteAuditRecord(DataGovernanceAuditRecord auditRecord, List`1 parameters, IIdentity logonIdentity)
                                    at Microsoft.Office.CompliancePolicy.Tasks.UnifiedPolicyAuditLogger.WriteCompliancePolicyAudit(Task cmdlet, PsCompliancePolicyBase policy, DataGovernanceAuditOperation operationType)
                                    at Microsoft.Office.CompliancePolicy.Tasks.NewRetentionCompliancePolicy.WriteResult(IConfigurable dataObject)
                                    at Microsoft.Exchange.Configuration.Tasks.NewTaskBase`1.WriteResult()
                                    at Microsoft.Office.CompliancePolicy.Tasks.NewCompliancePolicyBase.InternalProcessRecord()
                                    at Microsoft.Office.CompliancePolicy.Tasks.NewRetentionCompliancePolicy.InternalProcessRecord()
                                    at Microsoft.Exchange.Configuration.Tasks.Task.<ProcessRecord>b__104_1()
                                    at Microsoft.Exchange.Configuration.Tasks.Task.InvokeRetryableFunc(String funcName, Action func, Boolean terminatePipelineIfFailed)
                                    at Microsoft.Exchange.Configuration.Tasks.Task.ProcessTaskStage(TaskStage taskStage, Action initFunc, Action mainFunc, Action completeFunc)
                                    at Microsoft.Exchange.Configuration.Tasks.Task.ProcessRecord()
                                    at System.Management.Automation.CommandProcessor.ProcessRecord()
SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
ErrorRecord                    : Exception of type 'Microsoft.Office.Audit.Schema.ExpectedValueException' was thrown.
WasThrownFromThrowStatement    : False
TargetSite                     :
Message                        : Exception of type 'Microsoft.Office.Audit.Schema.ExpectedValueException' was thrown.
Data                           : {}
InnerException                 :
HelpLink                       :
Source                         :
HResult                        : -2146233087
StackTrace

When the connection is made in the context of a user through the UserprincipalName parameter there is no problem and everything works perfectly.
Connect-IPPSSession -userPrincipalName $User

**Comment by chrisda** [comment]
@jhosefer, because that version of the module is still in Preview, you can't open a regular support case about it (you can, but they won't be able to help you). Instead, you should send your information to the module support alias:

## Report bugs and issues for the EXO V2 module

When you report an issue at `exocmdletpreview[at]service[dot]microsoft[dot]com`, be sure to include the log files in your email message. To generate the log files, replace \<Path to store log file\> with the output folder you want, and run the following command:

```powershell
Connect-ExchangeOnline -EnableErrorReporting -LogDirectoryPath <Path to store log file> -LogLevel All
```

**Comment by yogkumgit** [comment]
@jhosefer Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
