### ISSUE TITLE
-BypassSecurityGroupManagerCheck not a recognized parameter 

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/office-docs-powershell#9985]
I don't believe -BypassSecurityGroupManagerCheck is valid anymore of Remove-DistributionGroupMember. See Error below when attempts are made to use it.

`2022-09-30T16:49:23Z   [Error]   ERROR: A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.

OriginInfo            : outlook.office365.com
Exception             : 
    Type                           : System.Management.Automation.RemoteException
    SerializedRemoteException      : System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                                     at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     --- End of stack trace from previous location where exception was thrown ---
                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
    ErrorRecord                    : 
        Exception             : 
            Type                           : System.Management.Automation.RemoteException
            SerializedRemoteException      : System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                                             at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                             at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             --- End of stack trace from previous location where exception was thrown ---
                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
            ErrorRecord                    : 
                Exception             : 
                    Type                           : System.Management.Automation.RemoteException
                    SerializedRemoteException      : System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                                                     at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     --- End of stack trace from previous location where exception was thrown ---
                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                    ErrorRecord                    : 
                        Exception             : 
                            Type                           : System.Management.Automation.RemoteException
                            SerializedRemoteException      : System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                                                             at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                             at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                             at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                             at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                             at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                             at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             --- End of stack trace from previous location where exception was thrown ---
                                                             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                             at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                             at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                            SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                            ErrorRecord                    : 
                                Exception             : 
                                    Type                           : System.Management.Automation.RemoteException
                                    SerializedRemoteException      : System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                                                                     at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                                                                     at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                                                                     at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                                                                     at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                                                                     at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     --- End of stack trace from previous location where exception was thrown ---
                                                                     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                                                     at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                                                                     at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
                                    SerializedRemoteInvocationInfo : System.Management.Automation.InvocationInfo
                                    ErrorRecord                    : …
                                    Message                        : A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                                    HResult                        : -2146233087
                                CategoryInfo          : InvalidArgument: (:) [Remove-DistributionGroupMember], ParameterBindingException
                                FullyQualifiedErrorId : NamedParameterNotFound,Remove-DistributionGroupMember
                            Message                        : A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                            HResult                        : -2146233087
                        CategoryInfo          : InvalidArgument: (:) [Remove-DistributionGroupMember], ParameterBindingException
                        FullyQualifiedErrorId : NamedParameterNotFound,Remove-DistributionGroupMember
                    Message                        : A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
                    HResult                        : -2146233087
                CategoryInfo          : InvalidArgument: (:) [Remove-DistributionGroupMember], ParameterBindingException
                FullyQualifiedErrorId : NamedParameterNotFound,Remove-DistributionGroupMember
            Message                        : A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
            HResult                        : -2146233087
        CategoryInfo          : InvalidArgument: (:) [Remove-DistributionGroupMember], ParameterBindingException
        FullyQualifiedErrorId : NamedParameterNotFound,Remove-DistributionGroupMember
    Message                        : A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'.
    HResult                        : -2146233087
CategoryInfo          : InvalidArgument: (:) [Remove-DistributionGroupMember], ParameterBindingException
FullyQualifiedErrorId : NamedParameterNotFound,Remove-DistributionGroupMember`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c15e59ac-c8d2-eb5e-deb0-711f09b3abe0
* Version Independent ID: 7b7e2adc-1ae1-abce-9028-28e7e3b4d66b
* Content: [Remove-DistributionGroupMember (ExchangePowerShell)](https://learn.microsoft.com/en-us/powershell/module/exchange/remove-distributiongroupmember?view=exchange-ps)
* Content Source: [exchange/exchange-ps/exchange/Remove-DistributionGroupMember.md](https://github.com/MicrosoftDocs/office-docs-powershell/blob/main/exchange/exchange-ps/exchange/Remove-DistributionGroupMember.md)
* Service: **exchange-powershell**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@jebalert, lots of questions.

The following command in my plain, nothing special E5 tenant shows that BypassSecurityGroupManagerCheck is available to me in Exchange Online:

```powershell
PS C:\Users\jdoe> (Get-Command Remove-DistributionGroupMember).parameters.keys | Sort-Object
AsJob
BypassSecurityGroupManagerCheck
Confirm
Debug
ErrorAction
ErrorVariable
Identity
InformationAction
InformationVariable
Member
OutBuffer
OutVariable
PipelineVariable
Verbose
WarningAction
WarningVariable
WhatIf
```

To eliminate RBAC issues, run the following commands:

```powershell
$Perms = Get-ManagementRole -Cmdlet Remove-DistributionGroupMember -CmdletParameters BypassSecurityGroupManagerCheck

$Perms | foreach {Get-ManagementRoleAssignment -Role $_.Name -Delegating $false | Format-Table -Auto Role,RoleAssigneeType,RoleAssigneeName}
```

This is what I get in my organization (obvious custom roles/role groups removed):

```powershell
Role                                   RoleAssigneeType RoleAssigneeName
----                                   ---------------- ----------------
Security Group Creation and Membership RoleGroup        Organization Management
```

After that, it gets down to connection methods:

- Are you using the latest version of the ExchangeOnlineManagement module (currently v3.0.0)?
- Does you use the UseRPSession switch in your connection command (old school remote PowerShell connection) or do you omit that switch for the newer REST API backed cmdlets experience?
- Or are you connecting using [app-only authentication](https://learn.microsoft.com/powershell/exchange/app-only-auth-powershell-v2) (a.k.a. certificate-based authentication or CBA)?

It's also possible that the parameter is available, but doesn't work correctly, although it would be very strange to receive the "A parameter cannot be found that matches parameter name" error in that case.

**Comment by jebalert** [comment]
Leveraging app only auth. The service principle has recipient management and manage as permissions. Module version is 2.0.5. I know that 3.0.0 came out this week. I don't believe UseRPSSession exists in 2.0.5

**Comment by chrisda** [comment]
Since you're using app-only auth, I would highly recommend [upgrading to v3.0.0](https://learn.microsoft.com/powershell/exchange/exchange-online-powershell-v2#update-the-exchange-online-powershell-module) and trying again.

**Comment by jebalert** [comment]
I'm going to look into this. I believe I made an attempt to update my requirements file earlier this week and had issues with assemblies. Do we know if v3.0.0 plays nicely with PowerShell runtime 7.0 in Azure Functions?

**Comment by chrisda** [comment]
No idea about Azure Functions.

**Comment by yogkumgit** [comment]
@jebalert Hope this comment is helpful for you. If you see a documentation update is required, please feel free to open an issue for the same. We proceed here to close it. Thanks for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.

**Comment by Weymire** [comment]
Hi! Bumping an old thread. I was trying to do some unattended scripts to do some stuff in our tennant such as removing inactive users from mail-enabled security groups in Exchange Online by using EXO v3 and got the same error for this particular parameter ("A parameter cannot be found that matches parameter name 'BypassSecurityGroupManagerCheck'."). I Created an app in App registration with self-signed cert authenitcation, granted API permissions (Graph User.Read/Write, Exchange.ManageAsApp and some others for testing purposes) and also added this service principle to Exchange with "Organization Managment" role. Everything seems to be working except for this parameter. I'm able for example to convert a mailbox to shared one, so this principle is deffinetely working and have some role assignments.

 - "BypassSecurityGroupManagerCheck" is only works when I'm authenticating with my Global Admin credentials;
 - I'm not using UseRPSession;
 - I've already tried to give this principle some different admin roles in Exchange and even in Azure, I even tried to give it Exchange Administrator assignment in Azure AD and it haven't changed anything sadly.

**Comment by chrisda** [comment]
@Weymire, confirm that you're having the issue in the latest version of the module (v3.3.0), and then open a support ticket about this. Report back here with any findings that can help improve the documentation.

**Comment by Weymire** [comment]
@chrisda Updated from 3.0.0 to 3.3.0, the issue still persists. Will open a new ticket and report back, thanks.

**Comment by Weymire** [comment]
False alarm. I can now confirm that updating to 3.3.0 has resolved the issue. Accidentally, I haven't updated the module on all the machines I've tried the script and this was the reason updating haven't worked. But now I can confirm that the issue occurs on both the 3.0.0 and 3.2.0 versions of the ExchangeOnline module, but 3.3.0 fixed it, thanks again!
